/*
*
*        _       _________ ______            _______  _______  _______  ______   _______  _______
*       ( \      \__   __/(  ___ \ |\     /|(  ___  )(       )(  ____ \(  ___ \ (  ____ )(  ____ \|\     /|
*       | (         ) (   | (   ) )| )   ( || (   ) || () () || (    \/| (   ) )| (    )|| (    \/| )   ( |
*       | |         | |   | (__/ / | (___) || |   | || || || || (__    | (__/ / | (____)|| (__    | | _ | |
*       | |         | |   |  __ (  |  ___  || |   | || |(_)| ||  __)   |  __ (  |     __)|  __)   | |( )| |
*       | |         | |   | (  \ \ | (   ) || |   | || |   | || (      | (  \ \ | (\ (   | (      | || || |
*       | (____/\___) (___| )___) )| )   ( || (___) || )   ( || (____/\| )___) )| ) \ \__| (____/\| () () |
*       (_______/\_______/|/ \___/ |/     \|(_______)|/     \|(_______/|/ \___/ |/   \__/(_______/(_______)
*
*
*
*/

#pragma once

#include "fw.h"

#ifdef FW_355

#define __printf 0x1df550
#define __copyin 0x3b96e0
#define __copyout 0x3b9660
#define __copyinstr 0x3b9a50
#define __kmem_alloc_contig 0x337ea0
#define __kmem_free 0x33bca0
#define __pmap_extract 0x3afd70
#define __pmap_protect 0x3b1f50
#define __sched_pin 0x1ced60
#define __sched_unpin 0x1cedc0
#define __smp_rendezvous 0x1e7810
#define __smp_no_rendevous_barrier 0x1e75d0
#define __icc_query_nowait 0x3ed450
#define __kernel_map 0x196acc8
#define __sysent 0xeed880
#define __kernel_pmap_store 0x19bd628
#define __Starsha_UcodeInfo 0x1869fa0

#define __pml4pml4i 0x19bd618
#define __dmpml4i 0x19bd61c
#define __dmpdpi 0x19bd620

#elif defined FW_370

#define __printf 0x1df620
#define __copyin 0x3b97d0
#define __copyout 0x3b9750
#define __copyinstr 0x3b9b40
#define __kmem_alloc_contig 0x337f70
#define __kmem_free 0x33bd70
#define __pmap_extract 0x3afe60
#define __pmap_protect 0x3b2040
#define __sched_pin 0x1cee30
#define __sched_unpin 0x1cee90
#define __smp_rendezvous 0x1e78e0
#define __smp_no_rendevous_barrier 0x1e76a0
#define __icc_query_nowait 0x3ed7f0
#define __kernel_map 0x1976cc8
#define __sysent 0xef6d90
#define __kernel_pmap_store 0x19c9628
#define __Starsha_UcodeInfo 0
#define __gpu_devid_is_9924 0x443a20
#define __gc_get_fw_info 0x44b5a0

#define __pml4pml4i 0x19c9618
#define __dmpml4i 0x19c961c
#define __dmpdpi 0x19c9620

#elif defined FW_400 || FW_401

#define __printf 0x347450
#define __copyin 0x286cc0
#define __copyout 0x286c40
#define __copyinstr 0x287030
#define __kmem_alloc_contig 0x275da0
#define __kmem_free 0x369580
#define __pmap_extract 0x3eeed0
#define __pmap_protect 0x3f1120
#define __sched_pin 0x1d1120
#define __sched_unpin 0x1d1180
#define __smp_rendezvous 0x34a020
#define __smp_no_rendevous_barrier 0x349de0
#define __icc_query_nowait 0x46c5a0
#define __kernel_map 0x1fe71b8
#define __sysent 0xf17790
#define __kernel_pmap_store 0x200c310
#define __Starsha_UcodeInfo 0x18dafb0

#define __pml4pml4i 0x200c300
#define __dmpml4i 0x200c304
#define __dmpdpi 0x200c308

#elif defined FW_405
#define __Xfast_syscall				     		        0x30EB30
#define __copyin					     			    0x286DF0
#define __copyout					     			    0x286D70
#define __copyinstr                                     0x287160
#define __copystr                                       0x2871F0
#define __printf			     					    0x347580
#define __device_printf                                 0x3FADB0
#define __vprintf                                       0x3475F0
#define __sprintf                                       0x347790
#define __snprintf                                      0x347860
#define __vsnprintf                                     0x347900
#define __vsnrprintf                                    0x347990
#define __kvprintf                                      0x347A00
#define __cnputc                                        0x14D20
#define __cnputs                                        0x15190
#define __strlen     								    0x1D3640
#define __malloc     								    0x1D1700
#define __free	     								    0x1D18D0
#define __memcpy	     						        0x286CF0
#define __memset	     							    0x1ECB10
#define __memcmp	     						        0x29CD10
#define __kmem_alloc     						        0x369500
#define __kmem_free                                     0x3696b0
#define __kmem_alloc_contig                             0x275ed0
#define __pmap_extract                                  0x3ef000
#define __pmap_protect                                  0x3f1250
#define __pmap_kextract                                 0x3EF390
#define __sched_pin                                     0x1d1250
#define __sched_unpin                                   0x1d12B0
#define __sched_switch                                  0x1D0040
#define __sched_bind                                    0x1D1120
#define __smp_rendezvous                                0x34a150
#define __smp_no_rendevous_barrier                      0x349f10
#define __kernel_pmap_store                             0x200c310
#define __kthread_add					     		    0x1C9890
#define __sx_init_flags					     		    0x27AAF0
#define __sx_xlock						     		    0x27AC20
#define __sx_xunlock					     		    0x27ADB0
#define __sx_destroy                                    0x27AB60
#define __fpu_kern_enter		     				    0x39A120
#define __fpu_kern_leave		     				    0x39A220
#define __vm_map_lock_read		     				    0x43DF10
#define __vm_map_lookup_entry	     				    0x43E470
#define __vm_map_unlock_read	     				    0x43DF60
#define __vmspace_free			     			        0x43DB70
#define __vmspace_acquire_ref     				        0x43DD40
#define __proc_rwmem		     					    0x0ABBB0
#define __bzero			     						    0x286C30
#define __pagezero 		     						    0x286C50
#define __bcmp			     						    0x286C80
#define __bcopy			     						    0x286CA0
#define __casuword32	     				            0x286E70
#define __kick_proc0      					            0x2168E0
#define __wakeup 	     							    0x8A7C0
#define __mi_switch 						     	    0x8A840
#define __eventlog_write_crash			     		    0x259180
#define __metadbg_perform_dump_on_panic                 0x71BAE0
#define __savectx                                       0x90B40
#define __savectx2                                      0x90BD0
#define __ktrcsw                                        0x2CF000
#define __sleepq_broadcast                              0x15FB70
#define __sleepq_remove                                 0x15FC30
#define __sleepq_release                                0x15ED50
#define __sleepq_lock                                   0x15ECD0
#define __hexdump                                       0x348DF0
#define __kern_reboot                                   0x25FC10
#define ____stack_chk_fail                              0x68F9B0
#define ___thread_lock_flags                            0x36E940
#define __vm_phys_paddr_to_vm_page                      0x3705C0
#define __critical_enter                                0x1E2660
#define __critical_exit                                 0x1E2670
#define __mutex_init                                    0x36EC70
#define __msgbuf_addchar                                0x36E640
#define __msgbufinit                                    0x348D90
#define __msgbuf_copy                                   0x73DA0
#define __msgbuf_getchar                                0x73AE0
#define __msgbuf_reinit                                 0x736D0
#define __msgbuf_addchar                                0x36E640
#define __msgbuf_addstr                                 0x738D0
#define __log                                           0x347360
#define __spinlock_enter                                0x38AC00
#define __spinlock_exit                                 0x38AC40
#define __icc_query                                     0x46BD80
#define __icc_query_nowait                              0x46c6d0
#define __icc_enable_crashmode                          0x46CBB0
#define __icc_nvs_write                                 0x46EFB0
#define __icc_nvs_read                                  0x470590
#define __icc_nvs_flush                                 0x4705F0
#define __icc_sc_config                                 0x1F51E0
#define __get_icc_max                                   0x21E010
#define __icc_wdt_start                                 0x71680
#define __icc_wdt_stop                                  0x71710
#define __panic0                                        0x101E40
#define __panic                                         0x2603B0
#define __kick_proc0                                    0x2168E0
#define __ssb_rtc_init_exclock                          0xE5C10
#define __ktrcsw                                        0x2CF000
#define ___mtx_lock_sleep                               0x36E260
#define ___mtx_unlock_sleep                             0x36E510
#define ___sleep                                        0x8A2E0
#define __uma_zfree_arg                                 0xB190
#define __uma_large_free                                0xC5A0
#define __uma_large_free_error                          0xC600
#define __lgdt                                          0x287220
#define __longjmp                                       0x287270
#define __pfs_create_dir                                0x1D97C0
#define __pfs_create_file                               0x1D9A50
#define __pfs_create_link                               0x1D9B60
#define __pfs_find_node                                 0x1D9D00
#define __sceSblPfsKeymgrGenEKpfsForGDGPAC     		    0x5FFE80
#define __sceSblPfsSetKey			     			    0x600640
#define __sceSblPfsClearKey		     				    0x6007C0
#define __sceSblACMgrIsAllowedSystemLevelDebugging      0x360570
#define __sceSblRcMgrIsAllowSLDebugger                  0x1E31F0
#define __sceSblAuthMgrIsLoadable                       0x611820
#define __sceSblAuthMgrAuthHeader                       0x611C10
#define __sceSblAuthMgrFinalize                         0x612330
#define __sceSblAuthMgrLoadBlock                        0x612490
#define ___sceSblAuthMgrGetElfSegmentInformation        0x6136F0
#define ___sceSblAuthMgrLoadSelfBlock                   0x614BB0
#define ___sceSblAuthMgrGetSelfSegmentInformation       0x615110
#define ___sceSblAuthMgrCheckSelfHeader                 0x615270
#define ___sceSblAuthMgrGetSelfInfo                     0x615360
#define ___sceSblAuthMgrSmDriveClearKey                 0x6154E0
#define ___sceSblAuthMgrSmDriveClearSessionKey          0x6155C0
#define ___sceSblAuthMgrSmDriveData                     0x6156A0
#define ___sceSblAuthMgrSmVerifyActCodeCommon           0x6158E0
#define ___sceSblAuthMgrSmGenActRequest                 0x615EF0
#define ___sceSblAuthMgrSmGenActHeader                  0x615AC0
#define ___sceSblAuthMgrSmGenPassCodeData               0x615CA0
#define ___sceSblAuthMgrSmCheckPassCodeData             0x615DC0
#define ___sceSblAuthMgrSmSpawn                         0x606E00
#define ___sceSblAuthMgrSmVerifyPupExpiration           0x606F40
#define __sceSblAuthMgrIsLoadable2	     			    0x614A80
#define __sceSblAuthMgrVerifyHeader	     		        0x614AE0
#define __sceSblAuthMgrGetSelfInfo     			 	    0x615360
#define __sceSblAuthMgrSmStart     				  	    0x6153F0
#define __sceSblKeymgrSmCallfunc	     			    0x5FF500
#define __sceSblServiceMailbox	     				    0x606F40
#define __sceSblServiceCrypt     					    0x5F7820
#define __sceSblServiceCryptAsync				        0x5F79B0
#define __sceSblSsGenerateSealedKey                     0x5FB4D0
#define __getSealedKeySecret                            0x5FB630
#define __sceSblSsDecryptSealedKey                      0x5FB800
#define __sceSblSsMemcmpConsttime                       0x600F10
#define __sceSblVtrmRestore 				            0x61ADE0
#define __sceSblVtrmBackup 				                0x61AD9E
#define __SceDaAtcev                                    0x37BDC0
#define __SceHidAuth                                    0x5D3330
#define __SceSflash           		     		        0x4B090
#define __sflash_pwrite_for_vtrm 	     			    0x4B380
#define __sflash_pread_for_vtrm  		     		    0x4B3F0
#define __sflash_erase_for_vtrm                         0x4B520
#define __VtrmUtilLockInitialize 	     			    0x6182E0
#define __VtrmUtilLockFinialize 	     			    0x618300
#define __vtrm_pread				                    0x6181E0
#define __vtrm_pwrite 				                    0x618209
#define __genNewActDat			     				    0x61E9F0
#define __AesCbcCfb128Encrypt	     		 		    0x19D650
#define __AesCbcCfb128Decrypt	     		 	 	    0x19D880
#define __AesEncKeySet 		     			            0x463950
#define __AesDecKeySet 		     			            0x464050
#define __AesEncrypt  		     			            0x4640A0
#define __AesDecrypt  		     			            0x4640E0
#define __Sha256HmacFinal	     			            0x3367B0
#define __Sha256Hash     	     			            0x3368E0
#define __Sha256Hmac      	     			            0x3369B0
#define __Sha256OneBlk   	     			            0x333810
#define __Sha256FinalCore 	     			            0x336300
#define __Sha256Init     	     			            0x3364C0
#define __Sha256Transform	     			            0x336510
#define __Sha256Final          				            0x336670
#define __Sha256HmacInit       				            0x3366C0
#define __sceSblRngGetRandomNumber				        0x61B690
#define __Fips186Prng 				                    0x183F40
#define __RsaesPkcs1v15Enc2048		     			    0x44C1C0
#define __RsaesPkcs1v15Dec2048CRT     				    0x1E82A0
#define __Starsha_UcodeInfo                             0
#define __gpu_devid_is_9924                             0x4b9030
#define __gc_get_fw_info                                0x4a19a0
#define __pml4pml4i                                     0x200c300
#define __dmpml4i                                       0x200c304
#define __dmpdpi                                        0x200c308
#define __sysent		     				            0xF17790
#define __allproc	     					            0x1FE3498
#define __disable_console_output		                0x186B0A0
#define __prison0						                0xF26010
#define __kernel_map					                0x1FE71B8
#define __rootvnode					     	            0x206D250
#define __M_TEMP				     		            0x134B730
#define __fpu_kern_ctx					                0x235C6C0
#define __mini_syscore_self_binary 		                0x136B3E8
#define __sbl_driver_mapped_pages  		                0x234ED68
#define __sbl_keymgr_key_rbtree	                        0x2370058

#elif defined FW_455

#define __Xfast_syscall				     		        0x3095D0
#define __printf                                        0x17F30
#define __copyin                                        0x14A890
#define __copyout                                       0x14A7B0
#define __copyinstr                                     0x14AD00

#define __copystr                                       0x2871F0
#define __strlen     								    0x1D3640
#define __vprintf                                       0x3475F0
#define __sprintf                                       0x347790
#define __snprintf                                      0x347860
#define __vsnprintf                                     0x347900
#define __vsnrprintf                                    0x347990
#define __sx_init_flags					     		    0x27AAF0
#define __sx_xlock						     		    0x27AC20
#define __sx_xunlock					     		    0x27ADB0
#define __sx_destroy                                    0x27AB60
#define __malloc     								    0x1D1700
#define __free	     								    0x1D18D0
#define __memcpy	     						        0x286CF0
#define __memset	     							    0x1ECB10
#define __memcmp	     						        0x29CD10
#define __sleepq_broadcast                              0x15FB70
#define __sleepq_remove                                 0x15FC30
#define __sleepq_release                                0x15ED50
#define __sleepq_lock                                   0x15ECD0
#define __sched_pin                                     0x1d1250
#define __sched_unpin                                   0x1d12B0
#define __sched_switch                                  0x1D0040
#define __sched_bind                                    0x1D1120
#define __fpu_kern_enter		     				    0x39A120
#define __fpu_kern_leave		     				    0x39A220
#define __icc_nvs_write                                 0x46EFB0
#define __icc_nvs_read                                  0x470590
#define __kthread_add					     		    0x1C9890
#define __proc_rwmem		     					    0x0ABBB0

#define __kmem_alloc_contig                             0x250320
#define __kmem_free                                     0x16EEA0
#define __pmap_extract                                  0x41DBC0
#define __pmap_protect                                  0x420310
#define __sched_pin                                     0x73770
#define __sched_unpinv                                  0x73780
#define __smp_rendezvous                                0xB2BB0
#define __smp_no_rendevous_barrier                      0xB2970
#define __icc_query_nowait                              0x808C0
#define __kernel_map                                    0x1B31218
#define __sysent                                        0x102B690
#define __kernel_pmap_store                             0x21BCC38
#define __Starsha_UcodeInfo                             0
#define __gpu_devid_is_9924                             0x496720
#define __gc_get_fw_info                                0x4A12D0
#define __disable_console_output                        0x1997BC8
#define __prison0                                       0x10399B0
#define __rootvnode                                     0x21AFA30
#define __pml4pml4i                                     0x21BCC28
#define __dmpml4i                                       0x21BCC2C
#define __dmpdpi                                        0x21BCC30
#define __sceSblSsDecryptSealedKey                      0x603580
#define __getSealedKeySecret                            0x603700

#elif defined FW_500 || FW_501 || FW_505

#define __Xfast_syscall                                 0x1C0
#define __printf                                        0x435C70
#define __copyin                                        0x1EA600
#define __copyout                                       0x1EA520
#define __copyinstr                                     0x1EAA30
#define __kmem_alloc_contig                             0xF1B80
#define __kmem_free                                     0xFCD40
#define __pmap_extract                                  0x2E02A0
#define __pmap_protect                                  0x2E2D00
#define __sched_pin                                     0x31FB70
#define __sched_unpin                                   0x31FB80
#define __smp_rendezvous                                0x1B84A0
#define __smp_no_rendevous_barrier                      0x1B8260
#define __icc_query_nowait                              0x44020
#define __kernel_map                                    0x1AC60E0
#define __sysent                                        0x107C610
#define __kernel_pmap_store                             0x22CB4F0
#define __Starsha_UcodeInfo                             0
#define __gpu_devid_is_9924                             0x4DDC40
#define __gc_get_fw_info                                0x4D33D0
#define __vprintf                                       0x435CE0
#define __cnputc                                        0x3DFAC0
#define ___thread_lock_flags                            0x402050
#define __spinlock_enter                                0x234960
#define __spinlock_exit                                 0x2349A0
#define __critical_enter                                0x28E4D0
#define __critical_exit                                 0x28E4E0
#define ___thread_lock_flags                            0x402050
#define __sched_bind                                    0x31FA50
#define ___mtx_lock_sleep                               0x401900
#define __vstrcmp                                       0x1D0EC0
#define __msgbuf_addstr                                 0x26C230
#define __snprintf                                      0x435F80
#define __log                                           0x435300
#define __sprintf                                       0x435EB0
#define __vsprintf                                      0x435F37
#define __vsnrprintf                                    0x4360B0
#define __vsnprintf                                     0x436020
#define __sprintf                                       0x435EB0
#define __kick_proc0                                    0x7210
#define __wakeup                                        0x3FB570
#define ___sx_sunlock_hard                              0xF69A0
#define ___sx_sunlock                                   0xF5E00
#define __kern_jail                                     0x3AB4C5
#define __priv_check_cred                               0x2FF820
#define __priv_check                                    0x2FF940
#define __prison_priv_check                             0x3B1D90
#define __sceSblACMgrIsSystemUcred                      0x11550
#define __sceSblACMgrIsSyscoreProcess                   0x11100
#define __sceSblACMgrHasUseVideoServiceCapability       0x10F90
#define __sceSblRcMgrIsAllowDataExecutionInFselfProcess 0x1D09A0
#define __vm_phys_paddr_to_vm_page                      0x298980
#define __pmap_kextract                                 0x2E0620
#define __uma_large_free                                0x22B670
#define __uma_zfree_arg                                 0x22A290
#define __kern_close                                    0xC0F40
#define __sx_xlock                                      0xF5D00
#define ___sx_xlock_hard                                0xF60A0
#define __audit_arg_fd                                  0x19D090
#define __currecord                                     0x3F94B0
#define __audit_arg_cmd                                 0x19D890
#define __kern_ioctl                                    0x153880
#define __malloc                                        0x10E140
#define __free                                          0x10E350
#define __bcopy                                         0xAB0
#define __strtol                                        0x218760
#define __disable_console_output                        0x19ECEB0
#define __prison0                                       0x10986A0                         
#define __rootvnode                                     0x
#define __pml4pml4i                                     0x22CB4E0
#define __dmpml4i                                       0x22CB4E4
#define __dmpdpi                                        0x22CB4E8
#define __sceSblSsDecryptSealedKey                      0x61F2A0
#define __getSealedKeySecret                            0x61F420

#endif
